import type { GenericSampleSceneInput } from '../genericSampleScene.js';

/** Learner-safe lower-primary mathematics and science samples for generic renderers. */
export const LOWER_PRIMARY_MATH_SCIENCE_SAMPLES = [
  {
    sceneId: 'ken-cbc-lower-primary.math-science.picture-choice-001',
    componentId: 'picture-choice',
    prompt: 'Which picture shows something that can be counted?',
    props: {
      title: 'Countable things around us',
      instructions: 'Choose one picture and tell a partner what you could count.',
      body: 'Look at the familiar objects below. Think about which group has separate objects.',
      options: [
        { id: 'mangoes', label: 'Mangoes in a basket' },
        { id: 'water', label: 'Water in a cup' },
        { id: 'sunshine', label: 'Sunshine' },
      ],
      inputKind: 'choice',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.number-manipulatives-001',
    componentId: 'number-manipulatives',
    prompt: 'Make 8 using bottle tops in two groups.',
    props: {
      title: 'Bottle-top groups',
      instructions: 'Move the bottle tops into two groups. Try a different way after you make 8.',
      body: 'Use the bottle tops like the ones used for sorting games in class.',
      items: [
        { id: 'tops-one', label: '4 bottle tops' },
        { id: 'tops-two', label: '4 bottle tops' },
      ],
      inputKind: 'numeric',
      inputLabel: 'How many bottle tops altogether?',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.phonics-sound-match-001',
    componentId: 'phonics-sound-match',
    prompt: 'Which word begins with the /m/ sound?',
    props: {
      title: 'Listen for /m/',
      instructions: 'Say each word slowly, then choose the word that starts with /m/.',
      options: [
        { id: 'mango', label: 'mango' },
        { id: 'sun', label: 'sun' },
        { id: 'goat', label: 'goat' },
      ],
      inputKind: 'choice',
      inputLabel: 'Word beginning with /m/',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.vocabulary-picture-match-001',
    componentId: 'vocabulary-picture-match',
    prompt: 'Match each word to a familiar thing.',
    props: {
      title: 'Words from home and school',
      instructions: 'Read a word aloud and choose the picture or object it names.',
      body: 'Use the words to practise speaking clearly with a classmate.',
      items: [
        { id: 'maize', label: 'maize' },
        { id: 'desk', label: 'desk' },
        { id: 'hen', label: 'hen' },
      ],
      options: [
        { id: 'maize-picture', label: 'A maize cob' },
        { id: 'desk-picture', label: 'A school desk' },
        { id: 'hen-picture', label: 'A hen' },
      ],
      inputKind: 'choice',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.reading-passage-001',
    componentId: 'reading-passage',
    prompt: 'Read about a morning at the school garden.',
    props: {
      title: 'The school garden',
      instructions: 'Read the passage aloud or quietly. Retell one thing that happened.',
      body: 'On Monday morning, Akinyi and her class watered the sukuma wiki in the school garden. They noticed a small bird near the fence. After watering, the learners returned the cans to the store.',
      inputKind: 'none',
      presentation: { canvas: { label: 'Reading passage', description: 'A clear space for reading the short passage.' } },
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.sentence-builder-001',
    componentId: 'sentence-builder',
    prompt: 'Build a sentence about the goat.',
    props: {
      title: 'Put the words in order',
      instructions: 'Arrange the word cards to make a sentence that makes sense.',
      items: [
        { id: 'the', label: 'The' },
        { id: 'goat', label: 'goat' },
        { id: 'eats', label: 'eats' },
        { id: 'grass', label: 'grass.' },
      ],
      inputKind: 'choice',
      inputLabel: 'Sentence order',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.handwriting-trace-001',
    componentId: 'handwriting-trace',
    prompt: 'Trace the letter M, then write it once on your own.',
    props: {
      title: 'Trace M for mango',
      instructions: 'Follow the letter shape with your finger or stylus. Then practise it in the space.',
      body: 'Use a gentle grip and start at the top of the letter.',
      inputKind: 'none',
      presentation: { canvas: { label: 'Handwriting practice area', description: 'A blank space for tracing and writing.' } },
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.rich-text-content-001',
    componentId: 'rich-text-content',
    prompt: 'Explore the parts of a healthy plant.',
    props: {
      title: 'A plant has different parts',
      instructions: 'Read the short notes and point to each part on a real plant if one is nearby.',
      body: 'Roots hold a plant in the soil. The stem supports the plant. Leaves help the plant make food. A flower can grow into a fruit.',
      steps: ['Read the notes.', 'Find a leaf or stem safely.', 'Tell a partner one job of a plant part.'],
      inputKind: 'none',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.single-choice-001',
    componentId: 'single-choice',
    prompt: 'Which shape has three sides?',
    props: {
      title: 'Shapes in our surroundings',
      instructions: 'Choose one shape, then look for a similar shape around the classroom.',
      options: [
        { id: 'triangle', label: 'Triangle' },
        { id: 'square', label: 'Square' },
        { id: 'circle', label: 'Circle' },
      ],
      inputKind: 'choice',
      inputLabel: 'Shape with three sides',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.fill-gap-001',
    componentId: 'fill-gap',
    prompt: 'Complete the sentence: A cow has ___ legs.',
    props: {
      title: 'Complete the animal fact',
      instructions: 'Type the number that completes the sentence.',
      body: 'Say the whole sentence aloud after you fill the gap.',
      inputKind: 'numeric',
      inputLabel: 'Number of legs',
      inputPlaceholder: 'Type a number',
      inputMaxLength: 1,
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.worked-example-001',
    componentId: 'worked-example',
    prompt: 'Follow the steps to add 6 and 3.',
    props: {
      title: 'Adding two small numbers',
      instructions: 'Read each step, then use counters to show the same idea.',
      steps: ['Start with 6 counters.', 'Add 3 more counters.', 'Count all the counters together.'],
      body: 'You can use beans, bottle tops, or small stones as counters.',
      inputKind: 'numeric',
      inputLabel: 'Total counters',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.number-line-001',
    componentId: 'number-line',
    prompt: 'Start at 4 and make two jumps forward.',
    props: {
      title: 'Jumps on a number line',
      instructions: 'Move along the line one step at a time. Record where you stop.',
      list: ['0', '1', '2', '3', '4', '5', '6', '7', '8'],
      inputKind: 'numeric',
      inputLabel: 'Number where you stop',
      presentation: { canvas: { label: 'Number-line movement area', description: 'A horizontal number line from 0 to 8.' } },
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.fraction-manipulative-001',
    componentId: 'fraction-manipulative',
    prompt: 'Show one half using the chapati pieces.',
    props: {
      title: 'Sharing a chapati fairly',
      instructions: 'Use the pieces to show two equal parts. Describe one part.',
      body: 'Imagine sharing one round chapati equally between two learners.',
      items: [
        { id: 'piece-a', label: 'Part A' },
        { id: 'piece-b', label: 'Part B' },
      ],
      inputKind: 'choice',
      inputLabel: 'Fraction shown',
      options: [
        { id: 'one-half', label: 'One half' },
        { id: 'one-third', label: 'One third' },
        { id: 'one-whole', label: 'One whole' },
      ],
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.measurement-lab-001',
    componentId: 'measurement-lab',
    prompt: 'Compare the lengths of a pencil and a book.',
    props: {
      title: 'Measure classroom objects',
      instructions: 'Use a ruler or hand spans. Record a measurement and compare the two objects.',
      steps: ['Place the ruler at the edge.', 'Read the length in centimetres.', 'Say which object is longer.'],
      body: 'Choose a pencil and a small exercise book from your desk.',
      inputKind: 'numeric',
      inputLabel: 'Pencil length in centimetres',
      inputPlaceholder: 'For example, 15',
      inputMaxLength: 2,
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.equation-builder-001',
    componentId: 'equation-builder',
    prompt: 'Build a number sentence for 5 birds and 2 more birds.',
    props: {
      title: 'Build an addition sentence',
      instructions: 'Arrange the cards to show the story with numbers and a plus sign.',
      body: 'Draw five birds, then draw two more if that helps you think.',
      items: [
        { id: 'five', label: '5' },
        { id: 'plus', label: '+' },
        { id: 'two', label: '2' },
        { id: 'equals', label: '=' },
        { id: 'seven', label: '7' },
      ],
      inputKind: 'choice',
      inputLabel: 'Number sentence order',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.data-table-chart-001',
    componentId: 'data-table-chart',
    prompt: 'Read the class fruit table and describe the biggest group.',
    props: {
      title: 'Fruit brought to class',
      instructions: 'Read each row. Use the table to compare the numbers.',
      table: {
        columns: ['Fruit', 'Number of learners'],
        rows: [['Banana', '6'], ['Mango', '4'], ['Orange', '3']],
      },
      inputKind: 'text',
      inputLabel: 'Fruit with the largest group',
      inputPlaceholder: 'Type a fruit name',
      inputMaxLength: 12,
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.labelled-science-diagram-001',
    componentId: 'labelled-science-diagram',
    prompt: 'Explore the parts of a bean seedling.',
    props: {
      title: 'Label a young plant',
      instructions: 'Choose a label and place it beside the part it names.',
      body: 'A bean seedling has roots below the soil, a stem, and small leaves above the soil.',
      items: [
        { id: 'roots', label: 'Roots' },
        { id: 'stem', label: 'Stem' },
        { id: 'leaves', label: 'Leaves' },
      ],
      inputKind: 'choice',
      presentation: { canvas: { label: 'Bean seedling diagram', description: 'A simple diagram area for placing plant-part labels.' } },
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.observation-table-001',
    componentId: 'observation-table',
    prompt: 'Record what you notice about two leaves.',
    props: {
      title: 'Leaf observation',
      instructions: 'Look closely without picking a living leaf. Record colour and texture.',
      table: {
        columns: ['Leaf', 'Colour', 'Texture'],
        rows: [['Leaf A', '', ''], ['Leaf B', '', '']],
      },
      inputKind: 'text',
      inputLabel: 'Your observation',
      inputPlaceholder: 'For example, green and smooth',
      inputMaxLength: 40,
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.virtual-lab-001',
    componentId: 'virtual-lab',
    prompt: 'Explore what happens when a shadow is made with a torch.',
    props: {
      title: 'Light and shadow',
      instructions: 'Move the object between the torch and the screen. Describe the shadow.',
      steps: ['Place the object near the torch.', 'Place it near the screen.', 'Compare the two shadows.'],
      options: [
        { id: 'larger', label: 'The shadow looks larger' },
        { id: 'smaller', label: 'The shadow looks smaller' },
        { id: 'same', label: 'The shadow looks the same' },
      ],
      inputKind: 'choice',
      inputLabel: 'What did you observe?',
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.glb-3d-model-viewer-001',
    componentId: 'glb-3d-model-viewer',
    prompt: 'Explore a 3D model of a bicycle and name two visible parts.',
    props: {
      title: 'Turn and inspect a bicycle',
      instructions: 'Rotate the model if available. Look at the wheels, seat, and handlebar.',
      body: 'Static fallback: A bicycle has two round wheels, a seat, pedals, and handlebars. Point to two parts in the picture or model.',
      steps: ['Look at the whole bicycle.', 'Find the two wheels.', 'Name another part you can see.'],
      inputKind: 'text',
      inputLabel: 'A bicycle part I can see',
      inputPlaceholder: 'Type one part',
      inputMaxLength: 20,
      presentation: { model: { label: 'Bicycle 3D model', description: 'An optional rotatable bicycle model; use the text fallback if unavailable.' } },
    },
  },
  {
    sceneId: 'ken-cbc-lower-primary.math-science.specimen-3d-explorer-001',
    componentId: 'specimen-3d-explorer',
    prompt: 'Explore a 3D model of a maize cob and describe its surface.',
    props: {
      title: 'Inspect a maize cob',
      instructions: 'Rotate or zoom the specimen if available. Observe its shape and texture.',
      body: 'Static fallback: A maize cob is long and has many kernels arranged in rows. Describe one feature you notice.',
      steps: ['Look at the shape.', 'Look for rows of kernels.', 'Share one observation.'],
      inputKind: 'text',
      inputLabel: 'Feature I noticed',
      inputPlaceholder: 'Type a short description',
      inputMaxLength: 40,
      presentation: { model: { label: 'Maize cob specimen', description: 'An optional rotatable maize cob model; use the text fallback if unavailable.' } },
    },
  },
] as const satisfies readonly GenericSampleSceneInput[];
