export type CountryOption = {
  code: 'KE' | 'UG' | 'TZ' | 'RW' | 'ET';
  name: 'Kenya' | 'Uganda' | 'Tanzania' | 'Rwanda' | 'Ethiopia';
  flag: string;
  curriculum: string;
  curriculumCode: 'CBC' | 'NCDC' | 'TIE-BASIC' | 'REB-CBC' | 'ENC';
  timeZones: readonly string[];
};

export const COUNTRY_OPTIONS: readonly CountryOption[] = [
  {
    code: 'KE',
    name: 'Kenya',
    flag: '\uD83C\uDDF0\uD83C\uDDEA',
    curriculum: 'CBC / KNEC Kenya curriculum',
    curriculumCode: 'CBC',
    timeZones: ['Africa/Nairobi'],
  },
  {
    code: 'UG',
    name: 'Uganda',
    flag: '\uD83C\uDDFA\uD83C\uDDEC',
    curriculum: 'Ugandan national curriculum',
    curriculumCode: 'NCDC',
    timeZones: ['Africa/Kampala'],
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    flag: '\uD83C\uDDF9\uD83C\uDDFF',
    curriculum: 'Tanzanian national curriculum',
    curriculumCode: 'TIE-BASIC',
    timeZones: ['Africa/Dar_es_Salaam'],
  },
  {
    code: 'RW',
    name: 'Rwanda',
    flag: '\uD83C\uDDF7\uD83C\uDDFC',
    curriculum: 'Rwandan CBC curriculum',
    curriculumCode: 'REB-CBC',
    timeZones: ['Africa/Kigali'],
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    flag: '\uD83C\uDDEA\uD83C\uDDF9',
    curriculum: 'Ethiopian national curriculum',
    curriculumCode: 'ENC',
    timeZones: ['Africa/Addis_Ababa'],
  },
] as const;

export const KENYAN_COUNTIES = [
  'Baringo',
  'Bomet',
  'Bungoma',
  'Busia',
  'Elgeyo-Marakwet',
  'Embu',
  'Garissa',
  'Homa Bay',
  'Isiolo',
  'Kajiado',
  'Kakamega',
  'Kericho',
  'Kiambu',
  'Kilifi',
  'Kirinyaga',
  'Kisii',
  'Kisumu',
  'Kitui',
  'Kwale',
  'Laikipia',
  'Lamu',
  'Machakos',
  'Makueni',
  'Mandera',
  'Marsabit',
  'Meru',
  'Migori',
  'Mombasa',
  "Murang'a",
  'Nairobi City',
  'Nakuru',
  'Nandi',
  'Narok',
  'Nyandarua',
  'Nyamira',
  'Nyeri',
  'Samburu',
  'Siaya',
  'Taita-Taveta',
  'Tana River',
  'Tharaka-Nithi',
  'Trans-Nzoia',
  'Turkana',
  'Uasin Gishu',
  'Vihiga',
  'Wajir',
  'West Pokot',
] as const;

export const UGANDA_DISTRICTS = [
  'Abim',
  'Adjumani',
  'Agago',
  'Alebtong',
  'Amolatar',
  'Amudat',
  'Amuria',
  'Amuru',
  'Apac',
  'Arua',
  'Budaka',
  'Bududa',
  'Bugiri',
  'Bugweri',
  'Buhweju',
  'Buikwe',
  'Bukedea',
  'Bukomansimbi',
  'Bukwo',
  'Bulambuli',
  'Buliisa',
  'Bundibugyo',
  'Bunyangabu',
  'Bushenyi',
  'Busia',
  'Butaleja',
  'Butambala',
  'Butebo',
  'Buvuma',
  'Buyende',
  'Dokolo',
  'Gomba',
  'Gulu',
  'Hoima',
  'Ibanda',
  'Iganga',
  'Isingiro',
  'Jinja',
  'Kaabong',
  'Kabale',
  'Kabarole',
  'Kaberamaido',
  'Kagadi',
  'Kakumiro',
  'Kalaki',
  'Kalangala',
  'Kaliro',
  'Kalungu',
  'Kampala',
  'Kamuli',
  'Kamwenge',
  'Kanungu',
  'Kapchorwa',
  'Kapelebyong',
  'Karenga',
  'Kasanda',
  'Kasese',
  'Katakwi',
  'Kayunga',
  'Kazo',
  'Kibaale',
  'Kiboga',
  'Kibuku',
  'Kikuube',
  'Kiruhura',
  'Kiryandongo',
  'Kisoro',
  'Kitagwenda',
  'Kitgum',
  'Koboko',
  'Kole',
  'Kotido',
  'Kumi',
  'Kwania',
  'Kween',
  'Kyankwanzi',
  'Kyegegwa',
  'Kyenjojo',
  'Kyotera',
  'Lamwo',
  'Lira',
  'Luuka',
  'Luweero',
  'Lwengo',
  'Lyantonde',
  'Madi-Okollo',
  'Manafwa',
  'Maracha',
  'Masaka',
  'Masindi',
  'Mayuge',
  'Mbale',
  'Mbarara',
  'Mitooma',
  'Mityana',
  'Moroto',
  'Moyo',
  'Mpigi',
  'Mubende',
  'Mukono',
  'Nabilatuk',
  'Nakapiripirit',
  'Nakaseke',
  'Nakasongola',
  'Namayingo',
  'Namisindwa',
  'Namutumba',
  'Napak',
  'Nebbi',
  'Ngora',
  'Ntoroko',
  'Ntungamo',
  'Nwoya',
  'Obongi',
  'Omoro',
  'Otuke',
  'Oyam',
  'Pader',
  'Pakwach',
  'Pallisa',
  'Rakai',
  'Rubanda',
  'Rubirizi',
  'Rukiga',
  'Rukungiri',
  'Rwampara',
  'Sembabule',
  'Serere',
  'Sheema',
  'Sironko',
  'Soroti',
  'Terego',
  'Tororo',
  'Wakiso',
  'Yumbe',
  'Zombo',
] as const;

export const UGANDA_CITIES = [
  'Arua City',
  'Entebbe City',
  'Fort Portal City',
  'Gulu City',
  'Hoima City',
  'Jinja City',
  'Kampala Capital City',
  'Lira City',
  'Masaka City',
  'Mbale City',
  'Mbarara City',
  'Soroti City',
] as const;

export const TANZANIA_REGIONS = [
  'Arusha',
  'Dar es Salaam',
  'Dodoma',
  'Geita',
  'Iringa',
  'Kagera',
  'Katavi',
  'Kigoma',
  'Kilimanjaro',
  'Lindi',
  'Manyara',
  'Mara',
  'Mbeya',
  'Mjini Magharibi',
  'Morogoro',
  'Mtwara',
  'Mwanza',
  'Njombe',
  'Pemba North',
  'Pemba South',
  'Pwani',
  'Rukwa',
  'Ruvuma',
  'Shinyanga',
  'Simiyu',
  'Singida',
  'Songwe',
  'Tabora',
  'Tanga',
  'Unguja North',
  'Unguja South',
] as const;

export const RWANDA_PROVINCES = [
  'Kigali City',
  'Northern Province',
  'Southern Province',
  'Eastern Province',
  'Western Province',
] as const;

export const ETHIOPIA_REGIONS = [
  'Addis Ababa',
  'Afar',
  'Amhara',
  'Benishangul-Gumuz',
  'Central Ethiopia',
  'Dire Dawa',
  'Gambela',
  'Harari',
  'Oromia',
  'Sidama',
  'Somali',
  'South Ethiopia',
  'South West Ethiopia Peoples',
  'Tigray',
] as const;

export const REGIONS_BY_COUNTRY: Record<
  CountryOption['code'],
  { label: string; labelSw: string; options: readonly string[] }
> = {
  KE: { label: 'County', labelSw: 'Kaunti', options: KENYAN_COUNTIES },
  UG: {
    label: 'District / City',
    labelSw: 'Wilaya / Jiji',
    options: [...UGANDA_DISTRICTS, ...UGANDA_CITIES],
  },
  TZ: { label: 'Region', labelSw: 'Mkoa', options: TANZANIA_REGIONS },
  RW: { label: 'Province', labelSw: 'Intara', options: RWANDA_PROVINCES },
  ET: { label: 'Region / Chartered City', labelSw: 'Jimbo / Jiji', options: ETHIOPIA_REGIONS },
};

export function detectDefaultCountryCode(): CountryOption['code'] {
  try {
    const zone = Intl.DateTimeFormat().resolvedOptions().timeZone ?? '';
    const match = COUNTRY_OPTIONS.find(option => option.timeZones.includes(zone));
    if (match) {
      return match.code;
    }
  } catch {
    // Intl is unavailable in a few test/runtime environments.
  }

  return 'KE';
}

export function countryCodeForName(name?: string | null): CountryOption['code'] {
  const normalized = (name || '').trim().toLowerCase();
  return COUNTRY_OPTIONS.find(option => option.name.toLowerCase() === normalized)?.code ?? 'KE';
}

export function countryNameForCode(code?: string | null): CountryOption['name'] {
  const normalized = (code || '').trim().toUpperCase();
  const aliases: Record<string, CountryOption['code']> = {
    KEN: 'KE',
    UGA: 'UG',
    TZA: 'TZ',
    RWA: 'RW',
    ETH: 'ET',
  };
  return COUNTRY_OPTIONS.find(option => option.code === (aliases[normalized] ?? normalized))?.name ?? 'Kenya';
}

export function curriculumCodeForCountry(code?: string | null) {
  const countryName = countryNameForCode(code);
  return COUNTRY_OPTIONS.find(option => option.name === countryName)?.curriculumCode ?? 'CBC';
}
