import type { OnboardingLanguageCode, OnboardingMascotKey, OnboardingVoiceName } from '../types/app';

const subjects: Record<string, string> = { English: 'Kiingereza', Kiswahili: 'Kiswahili', Mathematics: 'Hisabati', Environmental: 'Mazingira', CRE: 'CRE', IRE: 'IRE', HRE: 'HRE', 'Indigenous Languages': 'Lugha za Asili', 'Hygiene and Nutrition': 'Usafi na Lishe', 'Creative Activities': 'Shughuli za Ubunifu', 'Science & Technology': 'Sayansi na Teknolojia', 'Social Studies': 'Masomo ya Jamii', 'Religious Education': 'Elimu ya Dini', 'Creative Arts': 'Sanaa za Ubunifu', 'Agriculture & Nutrition': 'Kilimo na Lishe', Agriculture: 'Kilimo', 'Integrated Science': 'Sayansi Jumuishi', 'Pre-Technical Studies': 'Masomo ya Kabla ya Ufundi', 'Business Studies': 'Masomo ya Biashara', 'Creative Arts & Sports': 'Sanaa za Ubunifu na Michezo', 'Life Skills': 'Stadi za Maisha', Biology: 'Baiolojia', Chemistry: 'Kemia', Physics: 'Fizikia', 'Computer Studies': 'Masomo ya Kompyuta', 'Home Science': 'Sayansi ya Nyumbani', 'Drawing & Design': 'Uchoraji na Ubunifu', 'General Science': 'Sayansi ya Jumla', 'History & Citizenship': 'Historia na Uraia', Geography: 'Jiografia', 'Business Education': 'Elimu ya Biashara', 'CRE / IRE / HRE': 'CRE / IRE / HRE', French: 'Kifaransa', German: 'Kijerumani', Arabic: 'Kiarabu', Mandarin: 'Mandarin', 'Visual Arts': 'Sanaa za Kuonekana', 'Performing Arts': 'Sanaa za Maonyesho', Music: 'Muziki', 'Sports Science': 'Sayansi ya Michezo' };
const mascots: Record<OnboardingMascotKey, string> = { rabbit: 'Rafiki Sungura', lion: 'Rafiki Simba', elephant: 'Rafiki Tembo', panda: 'Rafiki Panda' };
const voices: Record<OnboardingVoiceName, string> = { Samora: 'Mchangamfu na mwenye kutia moyo', Barake: 'Mtulivu na wazi', Bella: 'Mchangamfu na mwenye nguvu', Judith: 'Mwenye subira na thabiti' };

export function parentHouseholdCopy(languageCode: OnboardingLanguageCode | null, childName = '', childIndex = 0, childCount = 1) {
  const sw = languageCode === 'sw';
  const child = childName.trim() || (sw ? 'mtoto wako' : 'your child');
  const learner = childName.trim() || `${sw ? 'Mwanafunzi' : 'Learner'} ${childIndex + 1}`;
  const englishMascot = (key: OnboardingMascotKey) => `Rafiki the ${key[0].toUpperCase()}${key.slice(1)}`;
  const tr = (en: string, swahili: string) => sw ? swahili : en;
  return {
    sw, prompt: 'Chagua Lugha Yako', kicker: tr('KITABU · ACCOUNT SETUP', 'KITABU · KUWEKA AKAUNTI'), language: 'Choose your language',
    title: { role: tr('Who are you?', 'Wewe ni nani?'), avatar: tr('Choose your avatar', 'Chagua picha yako'), name: tr('What is your name?', 'Unaitwa nani?'), whatsapp: tr('What is your WhatsApp number?', 'Nambari yako ya WhatsApp ni ipi?'), country: tr('Is This Your Country?', 'Je, hii ni nchi yako?'), childName: tr("What is Your Child's name?", 'Mtoto wako anaitwa nani?'), age: sw ? `${child} ana miaka mingapi?` : `How old is ${child}?`, gender: sw ? `Jinsia ya ${child} ni ipi?` : `What is ${child}'s gender?`, school: sw ? `${child} anasoma shule gani?` : `Where does ${child} go to school?`, grade: sw ? `${child} yuko darasa gani?` : `What grade is ${child} in?`, performance: sw ? `${child} anaendelea vipi na masomo?` : `How is ${child} performing?`, subjects: tr('Which subjects need help?', 'Ni masomo gani yanahitaji msaada?'), add: tr('Add another child?', 'Ongeza mtoto mwingine?'), microphone: tr('Allow microphone access', 'Ruhusu matumizi ya maikrofoni'), reminder: tr('Allow progress notifications', 'Ruhusu arifa za maendeleo'), referral: tr('How did you hear about Kitabu?', 'Ulisikiaje kuhusu Kitabu?'), tutor: tr('Choose Rafiki', 'Chagua Rafiki'), meet: tr('Meet Rafiki', 'Kutana na Rafiki'), voice: tr("Choose Rafiki's voice", 'Chagua sauti ya Rafiki'), social: tr('Practise makes Perfect', 'Mazoezi huleta mafanikio'), commitment: sw ? `Ahadi ya kila siku ya ${child}` : `${child}'s daily commitment`, readyChild: `${learner}${sw ? ' yuko tayari kujifunza!' : ' is ready to learn!'}`, loading: tr('Creating Your Study Plan', 'Tunatengeneza mpango wako wa masomo'), ready: tr('Your Study Plan is Ready!', 'Mpango wako wa masomo uko tayari!'), signup: tr('Save your family account', 'Hifadhi akaunti ya familia yako') },
    roleParent: tr('👨‍👩‍👧 Parent', '👨‍👩‍👧 Mzazi'), roleTeacher: tr('👩‍🏫 Teacher', '👩‍🏫 Mwalimu'), avatarLabel: tr('Choose parent avatar', 'Chagua picha ya mzazi'), mum: tr('Mum', 'Mama'), dad: tr('Dad', 'Baba'), namePlaceholder: tr('Your name', 'Jina lako'), whatsappPlaceholder: tr('WhatsApp number', 'Nambari ya WhatsApp'), whatsappCopy: tr("We will use this to send you reports about your child's progress", 'Tutatumia hii kukutumia taarifa kuhusu maendeleo ya mtoto wako'), childPlaceholder: tr("Child's name", 'Jina la mtoto'), agePlaceholder: tr('Age', 'Umri'), girl: tr('Girl', 'Msichana'), boy: tr('Boy', 'Mvulana'), continue: tr('Continue', 'Endelea'), saving: tr('Saving…', 'Inahifadhi…'), confirmCountry: tr('Confirm country', 'Thibitisha nchi'), back: tr('‹ Back', '‹ Rudi'),
    selectRegion: (label: string) => sw ? `Chagua ${label.toLowerCase()}` : `Select ${label.toLowerCase()}`, selectSchool: tr('Select school', 'Chagua shule'), country: tr('Choose another country', 'Chagua nchi nyingine'), curriculum: tr('curriculum', 'mtaala'), allAreas: tr('All Areas', 'Masomo yote'), grade: (value: string) => sw ? value.replace(/^Grade /, 'Darasa la ') : value, subject: (name: string) => sw ? subjects[name] ?? name : name,
    performance: (name: string) => sw ? ({ 'Far behind': 'Yuko nyuma sana', Behind: 'Yuko nyuma', 'At Grade Level': 'Yuko kwenye kiwango cha darasa', Ahead: 'Yuko mbele', 'Far Ahead': 'Yuko mbele sana', "I'm Not Sure": 'Sina uhakika' }[name] ?? name) : name,
    yesAdd: tr('Yes, add another child', 'Ndiyo, ongeza mtoto mwingine'), noContinue: tr('No, continue', 'Hapana, endelea'), notNow: tr('Not now', 'Si sasa'), allow: tr('Allow', 'Ruhusu'), microphoneCopy: tr('We need microphone access for spoken tutoring', 'Tunahitaji ruhusa ya maikrofoni kwa mafunzo ya kuzungumza'), reminderCopy: tr('Click Allow so as not to miss assignments and progress reports', 'Bonyeza Ruhusu ili usikose kazi na taarifa za maendeleo'), referral: (name: string) => sw ? ({ 'Friend or family': 'Rafiki au familia', 'School or teacher': 'Shule au mwalimu', Church: 'Kanisa', Search: 'Utafutaji', Other: 'Nyingine' }[name] ?? name) : name,
    tutorIntro: childIndex > 0 ? (sw ? `Sasa ni zamu ya ${learner} kuchagua Mwalimu wake` : `Now it’s ${learner}’s turn to select their Tutor`) : tr("Parent, please let the learner choose their tutor. Don't choose for them", 'Mzazi, tafadhali mwache mwanafunzi achague mwalimu wake. Usimchagulie.'), tutorIntroForChild: tr(`${learner} will choose their own tutor, voice, and commitment.`, `${learner} atachagua mwalimu, sauti na ahadi yake mwenyewe.`), mascot: (key: OnboardingMascotKey) => sw ? mascots[key] : englishMascot(key), rafiki: (key: OnboardingMascotKey) => sw ? `Habari mwanafunzi. Mimi ni ${mascots[key]} na nitakuwa mwalimu wako. Uko tayari kujifunza?` : `Hi learner. My name is ${englishMascot(key)} and I will be your Tutor. Are you ready to learn?`, voice: (name: OnboardingVoiceName) => sw ? voices[name] : ({ Samora: 'Warm and encouraging', Barake: 'Calm and clear', Bella: 'Bright and energetic', Judith: 'Patient and steady' }[name]), preview: tr('Preview voice', 'Sikiliza sauti'), playing: tr('Playing…', 'Inacheza…'), previewDone: tr('Preview complete', 'Usikilizaji umekamilika'),
    social: tr('89% of learners who practice for at least 20 minutes every day improve their grades in less than 1 month', '89% ya wanafunzi wanaofanya mazoezi kwa angalau dakika 20 kila siku huboresha alama zao kwa chini ya mwezi mmoja'), commitmentPrompt: sw ? `${learner}, uko tayari kufanya ahadi hiyo?` : `${learner}, are you ready to make that commitment?`, no: tr('No', 'Hapana'), yes: tr('Yes', 'Ndiyo'), sign: tr('Sign here', 'Saini hapa'), draw: tr('Draw your signature', 'Chora saini yako'), signed: (name: string) => sw ? `✓ Imesainiwa na ${name || learner}` : `✓ Signed by ${name || learner}`, readyCopy: tr('Great choice—Rafiki is ready to begin.', 'Chaguo zuri—Rafiki yuko tayari kuanza.'), readyText: (country: string) => sw ? `${childCount} ${childCount === 1 ? 'mwanafunzi' : 'wanafunzi'} · ${country} · mazoezi ya kila siku` : `${childCount} learner${childCount === 1 ? '' : 's'} · ${country} · daily practice`, readyRow: (name: string, index: number) => sw ? `✓ Mpango wa masomo wa ${name || `Mtoto ${index + 1}`} umetayarishwa` : `✓ ${name || `Child ${index + 1}`} study plan prepared`,
    signupCopy: tr('Keep your children’s plans, progress reports, and tutor settings together.', 'Weka mipango ya watoto wako, taarifa za maendeleo na mipangilio ya walimu pamoja.'), google: tr('Continue with Google', 'Endelea na Google'), email: tr('or use email', 'au tumia barua pepe'), emailPlaceholder: tr('Email', 'Barua pepe'), password: tr('Password', 'Nenosiri'), confirmPassword: tr('Confirm password', 'Thibitisha nenosiri'), show: tr('Show', 'Onyesha'), hide: tr('Hide', 'Ficha'),
    studyPlanMessages: sw ? ['Tunaangalia mtaala', 'Tunaongeza maswali', 'Tunaongeza michezo', 'Tunatafuta wanafunzi wenzako', 'Tunaongeza burudani', 'Tunatafuta walimu wako', 'Tunafanya maswali yawe magumu', 'Tunaongeza mwakenya', 'Tunatania tu', 'Tunaongeza uchawi'] : ['Checking curriculum', 'Adding quizzes', 'Adding games', 'Finding your classmates', 'Adding more fun', 'Finding your teachers', 'Making quizzes harder', 'Adding mwakenya', 'Just kidding', 'Throwing in some magic'], schoolNameValidation: tr('Enter a school name and select a county first.', 'Andika jina la shule na uchague kaunti kwanza.'),
    validation: { language: tr('Choose a language to continue.', 'Chagua lugha ili uendelee.'), avatar: tr('Choose an avatar to continue.', 'Chagua picha ili uendelee.'), name: tr('Enter your name to continue.', 'Andika jina lako ili uendelee.'), whatsapp: tr('Enter a valid WhatsApp number with 9–20 characters and at least 9 digits.', 'Andika nambari halali ya WhatsApp yenye alama 9–20 na angalau tarakimu 9.'), childName: tr("Enter your child's name to continue.", 'Andika jina la mtoto wako ili uendelee.'), age: tr('Age must be between 4 and 20.', 'Umri lazima uwe kati ya 4 na 20.'), gender: tr('Choose Girl or Boy to continue.', 'Chagua Msichana au Mvulana ili uendelee.'), school: tr('Select a county and school to continue.', 'Chagua kaunti na shule ili uendelee.'), grade: tr('Select a grade to continue.', 'Chagua darasa ili uendelee.'), performance: tr('Choose a performance level to continue.', 'Chagua kiwango cha ufaulu ili uendelee.'), subjects: tr('Select at least one subject.', 'Chagua angalau somo moja.'), referral: tr('Choose how you heard about Kitabu.', 'Chagua ulivyosikia kuhusu Kitabu.'), tutor: tr('Choose a tutor to continue.', 'Chagua mwalimu ili uendelee.'), voice: tr('Choose a tutor voice to continue.', 'Chagua sauti ya mwalimu ili uendelee.'), commitment: tr('Choose Yes to make the commitment.', 'Chagua Ndiyo kufanya ahadi.'), sign: tr('Sign before continuing.', 'Saini kabla ya kuendelea.'), email: tr('Enter a valid email address.', 'Andika barua pepe halali.'), password: tr('Use at least 8 characters for your password.', 'Tumia angalau herufi 8 kwa nenosiri lako.'), match: tr('Passwords do not match.', 'Manenosiri hayalingani.') },
  };
}
