import argparse
import json
import os
import time
import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps


PAGE_SIZE = (1240, 1754)
MARGIN = 86


def load_font(size, bold=False):
    candidates = [
        Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf"),
        Path("C:/Windows/Fonts/calibrib.ttf" if bold else "C:/Windows/Fonts/calibri.ttf"),
        Path("C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


TITLE_FONT = load_font(52, True)
H1_FONT = load_font(34, True)
BODY_FONT = load_font(24)
SMALL_FONT = load_font(18)


def text_width(draw, text, font):
    return draw.textbbox((0, 0), text, font=font)[2]


def wrap_lines(draw, text, font, max_width):
    lines = []
    for paragraph in str(text).splitlines():
        if not paragraph.strip():
            lines.append("")
            continue
        words = paragraph.split()
        current = ""
        for word in words:
            attempt = f"{current} {word}".strip()
            if text_width(draw, attempt, font) <= max_width or not current:
                current = attempt
            else:
                lines.append(current)
                current = word
        if current:
            lines.append(current)
    return lines


def draw_wrapped(draw, text, x, y, font, fill, max_width, line_height):
    for line in wrap_lines(draw, text, font, max_width):
        if line:
            draw.text((x, y), line, font=font, fill=fill)
        y += line_height
    return y


def new_page(bg="#FFFFFF"):
    image = Image.new("RGB", PAGE_SIZE, bg)
    draw = ImageDraw.Draw(image)
    return image, draw


def render_cover(manifest):
    color = manifest.get("subjectColor") or "#0F766E"
    image, draw = new_page(color)
    draw.rectangle((44, 44, PAGE_SIZE[0] - 44, PAGE_SIZE[1] - 44), outline="#FFFFFF", width=6)
    y = 180
    y = draw_wrapped(draw, "KITABU QUEST", MARGIN, y, TITLE_FONT, "#FFFFFF", PAGE_SIZE[0] - 2 * MARGIN, 64)
    y += 28
    y = draw_wrapped(draw, manifest.get("grade", ""), MARGIN, y, H1_FONT, "#FEF3C7", PAGE_SIZE[0] - 2 * MARGIN, 44)
    y = draw_wrapped(draw, manifest.get("subject", ""), MARGIN, y, TITLE_FONT, "#FFFFFF", PAGE_SIZE[0] - 2 * MARGIN, 62)
    mascot = manifest.get("mascot") or {}
    scene = (manifest.get("cover") or {}).get("scene", "")
    y += 42
    draw.rounded_rectangle((MARGIN, y, PAGE_SIZE[0] - MARGIN, y + 280), radius=24, fill="#FFFFFF")
    draw_wrapped(
        draw,
        f"Mascot: {mascot.get('species', 'assigned mascot')}\nScene: {scene}\nCBC aligned draft learner book",
        MARGIN + 34,
        y + 34,
        H1_FONT,
        "#111827",
        PAGE_SIZE[0] - 2 * MARGIN - 68,
        44,
    )
    draw.text((MARGIN, PAGE_SIZE[1] - 180), "Think • Explore • Achieve", font=H1_FONT, fill="#FFFFFF")
    draw.text((MARGIN, PAGE_SIZE[1] - 120), "Generated by Kitabu AI Learning Studio", font=SMALL_FONT, fill="#F8FAFC")
    return image


def load_package_cover(package_dir, manifest):
    cover_path = package_dir / "assets" / "cover.png"
    if cover_path.exists():
        return ImageOps.fit(Image.open(cover_path).convert("RGB"), PAGE_SIZE, method=Image.Resampling.LANCZOS)
    return render_cover(manifest)


def render_package(package_dir):
    package_dir = Path(package_dir)
    manifest = json.loads((package_dir / "manifest.json").read_text(encoding="utf-8"))
    pages = json.loads((package_dir / "pages.json").read_text(encoding="utf-8"))
    if isinstance(pages, dict):
        pages = pages.get("pages", [])

    rendered = [load_package_cover(package_dir, manifest)]
    current, draw = new_page()
    y = MARGIN

    for index, page in enumerate(pages, start=1):
        title = page.get("title") or f"Page {index}"
        content = page.get("content") or ""
        blocks = [("#", title), ("", content)]
        for kind, block in blocks:
            font = H1_FONT if kind == "#" else BODY_FONT
            fill = "#111827"
            line_height = 46 if kind == "#" else 34
            for paragraph in str(block).split("\n\n"):
                needed = len(textwrap.wrap(paragraph, width=78)) * line_height + 22
                if y + needed > PAGE_SIZE[1] - MARGIN:
                    draw.text((PAGE_SIZE[0] - MARGIN - 130, PAGE_SIZE[1] - 58), str(len(rendered)), font=SMALL_FONT, fill="#6B7280")
                    rendered.append(current)
                    current, draw = new_page()
                    y = MARGIN
                y = draw_wrapped(draw, paragraph, MARGIN, y, font, fill, PAGE_SIZE[0] - 2 * MARGIN, line_height)
                y += 18
        y += 18

    rendered.append(current)
    pdf_path = package_dir / f"{manifest['bookId']}.pdf"
    tmp_path = package_dir / f"{manifest['bookId']}.pdf.tmp"
    rendered[0].save(tmp_path, "PDF", resolution=150.0, save_all=True, append_images=rendered[1:])
    replace_pdf(tmp_path, pdf_path)
    print(json.dumps({"pdf": str(pdf_path), "pages": len(rendered)}, indent=2))


def replace_pdf(tmp_path, pdf_path):
    last_error = None
    for attempt in range(6):
        try:
            os.replace(tmp_path, pdf_path)
            return
        except PermissionError as error:
            last_error = error
            try:
                pdf_path.unlink(missing_ok=True)
            except PermissionError:
                pass
            time.sleep(0.25 * (attempt + 1))
    raise last_error


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dir", required=True)
    args = parser.parse_args()
    render_package(args.dir)


if __name__ == "__main__":
    main()
